kind: Service
apiVersion: v1
metadata:
  namespace: gitlab-managed-apps
  name: ${APP_NAME}
spec:
  selector:
    app: ${APP_NAME}
  type: NodePort
  ports:
     - nodePort: 32028
       protocol: TCP
       port: 80
       targetPort: 80
---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: gitlab-managed-apps
  name: ${APP_NAME}
  labels:
    app: ${APP_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APP_NAME}
  template:
    metadata:
      labels:
        app: ${APP_NAME}
    spec:
      imagePullSecrets:
        - name: gitlab-auth
      containers:
        - name: ${APP_NAME}
          image: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}
          ports:
            - containerPort: 80
          imagePullPolicy: Always
